<?php

namespace Ais\KontrakDosenBundle\Repository;

/**
 * KontrakDosenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KontrakDosenRepository extends \Doctrine\ORM\EntityRepository
{
}
